FROM ghcr.io/puppeteer/puppeteer:24.4.0

# Install dependencies, including Google Chrome
RUN apt update && apt install -y google-chrome-stable

# Environment variables for Puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

# Set working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of the app files
COPY . .

# Run the application
CMD ["node", "dist/index.js"]
